name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      #- uses: actions-hub/kubectl@master
      - name: create Kubeconfig
        run:
          mkdir ${HOME}/.kube
          echo ${{secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - name: use context
        run: kubectl config use-context ns-kyn-001160-rcp-poc-dev/api-xxoueqiy-eastus-aroapp-io:6443/tharuna.maddipudi@kyndryl.com
      - name: pods list
        run: kubectl get pods
        #env:
         # KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }} | base64 --decode 
        #with:
          #args: get pods
