name: POD's Check
on: [push]
env:
  OPENSHIFT_SERVER: api.xxoueqiy.eastus.aroapp.io
jobs:
  deploy:
    name: POD's Check-in
    runs-on: ubuntu-latest
    steps:
      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.xxoueqiy.eastus.aroapp.io:6443
          openshift_token: sha256~tAQheXrvjvNMa-Ce0TClH1ruXLG2-7IjYWgXBzM-q0g
          namespace: ns-kyn-001160-rcp-poc-dev
          openshift_username: tharuna.maddipudi@kyndryl.com/api-xxoueqiy-eastus-aroapp-io:6443
          insecure_skip_tls_verify: true
          reveal_cluster_name: false
      - uses: actions-hub/kubectl@master
        with:
          args: get pods
