name: Connect & Check OpenShift Cluster
on: [push]
env:
  OPENSHIFT_SERVER: api.xxoueqiy.eastus.aroapp.io

jobs:
  run:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: LOGIN
      uses: redhat-developer/openshift-actions@v1.1
      with:
          openshift_server_url: https://api.xxoueqiy.eastus.aroapp.io:6443
          openshift_token: sha256~71FkaN6hEwzch48VIJagoZxm7x9aWubElHeoh3zg-rw
          namespace: ns-kyn-001160-rcp-poc-dev
          openshift_username: tharuna.maddipudi@kyndryl.com/api-xxoueqiy-eastus-aroapp-io:6443
          insecure_skip_tls_verify: true
          reveal_cluster_name: false
    - name: CHECK
      run: oc get pods
        
